const fs = require('fs');
const path = require('path');

const POLYFILL_LINE = `// SQLite enum polyfills`;

const ENUMS_CODE = `
${POLYFILL_LINE}
Object.assign(module.exports, {
  UserRole: {
    SUPER_ADMIN: 'SUPER_ADMIN', CHANCELLOR: 'CHANCELLOR', VICE_CHANCELLOR: 'VICE_CHANCELLOR',
    REGISTRAR: 'REGISTRAR', FINANCE: 'FINANCE', ACADEMIC_OFFICE: 'ACADEMIC_OFFICE',
    EXAMINATION_DEPT: 'EXAMINATION_DEPT', LIBRARY_STAFF: 'LIBRARY_STAFF',
    HOSTEL_OFFICE: 'HOSTEL_OFFICE', TRANSPORT_OFFICE: 'TRANSPORT_OFFICE',
    TNP_CELL: 'TNP_CELL', DEPARTMENT_HEAD: 'DEPARTMENT_HEAD', FACULTY: 'FACULTY',
    ASSISTANT_PROFESSOR: 'ASSISTANT_PROFESSOR', LECTURER: 'LECTURER', STUDENT: 'STUDENT',
    GUARDIAN: 'GUARDIAN', ALUMNI: 'ALUMNI', SECURITY_STAFF: 'SECURITY_STAFF',
    MAINTENANCE_STAFF: 'MAINTENANCE_STAFF', RECEPTION: 'RECEPTION',
    SUPPORT_AGENT: 'SUPPORT_AGENT', GUEST: 'GUEST',
  },
  Gender: { MALE: 'MALE', FEMALE: 'FEMALE', OTHER: 'OTHER' },
  BloodGroup: { A_POSITIVE: 'A_POSITIVE', A_NEGATIVE: 'A_NEGATIVE', B_POSITIVE: 'B_POSITIVE', B_NEGATIVE: 'B_NEGATIVE', AB_POSITIVE: 'AB_POSITIVE', AB_NEGATIVE: 'AB_NEGATIVE', O_POSITIVE: 'O_POSITIVE', O_NEGATIVE: 'O_NEGATIVE' },
  MaritalStatus: { SINGLE: 'SINGLE', MARRIED: 'MARRIED', DIVORCED: 'DIVORCED', WIDOWED: 'WIDOWED' },
  HostelRoomType: { SINGLE: 'SINGLE', DOUBLE: 'DOUBLE', TRIPLE: 'TRIPLE', DORM: 'DORM' },
  HostelRoomStatus: { AVAILABLE: 'AVAILABLE', OCCUPIED: 'OCCUPIED', MAINTENANCE: 'MAINTENANCE', RESERVED: 'RESERVED' },
  ComplaintPriority: { LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH', URGENT: 'URGENT' },
  ComplaintStatus: { OPEN: 'OPEN', IN_PROGRESS: 'IN_PROGRESS', RESOLVED: 'RESOLVED', CLOSED: 'CLOSED' },
  FeeStatus: { PENDING: 'PENDING', PARTIAL: 'PARTIAL', PAID: 'PAID', OVERDUE: 'OVERDUE', WAIVED: 'WAIVED' },
  PaymentMode: { CASH: 'CASH', CHEQUE: 'CHEQUE', ONLINE: 'ONLINE', UPI: 'UPI', CARD: 'CARD', BANK_TRANSFER: 'BANK_TRANSFER' },
  LeaveType: { CASUAL: 'CASUAL', SICK: 'SICK', EARNED: 'EARNED', MATERNITY: 'MATERNITY', PATERNITY: 'PATERNITY', UNPAID: 'UNPAID', OTHER: 'OTHER' },
  LeaveStatus: { PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED', CANCELLED: 'CANCELLED' },
  LibraryItemType: { BOOK: 'BOOK', JOURNAL: 'JOURNAL', MAGAZINE: 'MAGAZINE', THESIS: 'THESIS', CD: 'CD', DVD: 'DVD', OTHER: 'OTHER' },
  LibraryItemStatus: { AVAILABLE: 'AVAILABLE', ISSUED: 'ISSUED', RESERVED: 'RESERVED', UNDER_MAINTENANCE: 'UNDER_MAINTENANCE', LOST: 'LOST', WITHDRAWN: 'WITHDRAWN' },
  TransportRouteType: { BUS: 'BUS', VAN: 'VAN', AUTO: 'AUTO', OTHER: 'OTHER' },
  NotificationType: { INFO: 'INFO', WARNING: 'WARNING', ALERT: 'ALERT', REMINDER: 'REMINDER', PROMOTION: 'PROMOTION' },
  ApplicationType: { ADMISSION: 'ADMISSION', TRANSFER: 'TRANSFER', SCHOLARSHIP: 'SCHOLARSHIP', LEAVE: 'LEAVE', OTHER: 'OTHER' },
  StudentStatus: { ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE', GRADUATED: 'GRADUATED', SUSPENDED: 'SUSPENDED', WITHDRAWN: 'WITHDRAWN' },
  EmployeeType: { PERMANENT: 'PERMANENT', CONTRACT: 'CONTRACT', VISITING: 'VISITING', ADJUNCT: 'ADJUNCT' },
  AttendanceStatus: { PRESENT: 'PRESENT', ABSENT: 'ABSENT', LATE: 'LATE', HALF_DAY: 'HALF_DAY', HOLIDAY: 'HOLIDAY' },
  AssetStatus: { AVAILABLE: 'AVAILABLE', IN_USE: 'IN_USE', UNDER_MAINTENANCE: 'UNDER_MAINTENANCE', RETIRED: 'RETIRED', LOST: 'LOST', DAMAGED: 'DAMAGED' },
  AttendanceSession: { MORNING: 'MORNING', AFTERNOON: 'AFTERNOON', EVENING: 'EVENING' },
  ExamType: { MIDTERM: 'MIDTERM', FINAL: 'FINAL', QUIZ: 'QUIZ', ASSIGNMENT: 'ASSIGNMENT', PRACTICAL: 'PRACTICAL', PROJECT: 'PROJECT' },
  GradeStatus: { PASS: 'PASS', FAIL: 'FAIL', INCOMPLETE: 'INCOMPLETE', WITHDRAWN: 'WITHDRAWN' },
  TrainingType: { TECHNICAL: 'TECHNICAL', SOFT_SKILL: 'SOFT_SKILL', MANAGEMENT: 'MANAGEMENT', OTHER: 'OTHER' },
  DocumentType: { ID_PROOF: 'ID_PROOF', CERTIFICATE: 'CERTIFICATE', TRANSCRIPT: 'TRANSCRIPT', OTHER: 'OTHER' },
  EventType: { ACADEMIC: 'ACADEMIC', CULTURAL: 'CULTURAL', SPORTS: 'SPORTS', WORKSHOP: 'WORKSHOP', SEMINAR: 'SEMINAR', OTHER: 'OTHER' },
  AdmissionStatus: { APPLIED: 'APPLIED', ACCEPTED: 'ACCEPTED', REJECTED: 'REJECTED', WAITLISTED: 'WAITLISTED', ENROLLED: 'ENROLLED' },
  EnrollmentStatus: { ACTIVE: 'ACTIVE', INACTIVE: 'INACTIVE', GRADUATED: 'GRADUATED', SUSPENDED: 'SUSPENDED', WITHDRAWN: 'WITHDRAWN', COMPLETED: 'COMPLETED' },
  ResearchStatus: { PROPOSED: 'PROPOSED', IN_PROGRESS: 'IN_PROGRESS', COMPLETED: 'COMPLETED', PUBLISHED: 'PUBLISHED', ON_HOLD: 'ON_HOLD' },
});
`;

function polyfillFile(filePath) {
  if (!fs.existsSync(filePath)) return false;
  let content = fs.readFileSync(filePath, 'utf8');
  if (content.includes(POLYFILL_LINE)) {
    const polyfillStart = content.indexOf(POLYFILL_LINE);
    content = content.substring(0, polyfillStart).trimEnd();
  }
  
  content = content + '\n' + ENUMS_CODE;
  
  fs.writeFileSync(filePath, content);
  return true;
}

const clientDir = path.join(__dirname, 'node_modules', '@prisma', 'client');
for (const fname of ['default.js', 'index.js']) {
  const fullPath = path.join(clientDir, fname);
  if (polyfillFile(fullPath)) {
    console.log('Polyfilled', fname);
  }
}
